# Generated by Django 3.2.9 on 2022-03-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(max_length=50)),
                ('Book_Category', models.CharField(max_length=50)),
                ('Book_Author', models.CharField(max_length=50)),
                ('Book_Price', models.FloatField()),
            ],
        ),
    ]
